version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: embedchain-backend
    volumes:
      - ./backend:/usr/src/app/backend
      - backend_data:/usr/src/app/backend/database
    ports:
      - "25046:25046"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: embedchain-frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/.next
    ports:
      - "25047:25047"
    depends_on:
      - backend

volumes:
  backend_data:
